name: Build and deploy jekyll site

on:
  push:
    branches:
      - dev

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v2
      
      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Dependencies
        run: |
          wget http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/main/libw/libwebp/libwebpdemux2_0.6.1-2ubuntu0.20.04.3_amd64.deb
          wget http://azure.archive.ubuntu.com/ubuntu/pool/main/p/poppler/libpoppler97_0.86.1-0ubuntu1.3_amd64.deb
          wget http://azure.archive.ubuntu.com/ubuntu/pool/main/p/poppler/libpoppler-glib8_0.86.1-0ubuntu1.3_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/v/vips/libvips42_8.9.1-2_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/v/vips/libvips-tools_8.9.1-2_amd64.deb
          sudo apt install ./*.deb

      - name: 🔨 Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2.4.1
        with:
          enable_cache: true
          format_output: true
          prettier_opts: '{ "useTabs": true }'
          
      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main
