name: Build and deploy jekyll site

on:
  push:
    branches:
      - dev

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v2
      
      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Dependencies via apt
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi6 libwebpdemux2 libpoppler97 libpoppler-glib8 libvips42 libvips-tools

      - name: 🔨 Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2.4.1
        with:
          enable_cache: true
          format_output: true
          prettier_opts: '{ "useTabs": true }'
          
      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main
